export const songSearchParamsMap = {
  primaryColor: 'primary-color',
  secondaryColor: 'secondary-color',
  height: 'height',
  width: 'width',
  titleDropShadowEnabled: 'title-drop-shadow',
  titleDropShadowSettings: 'title-drop-shadow-settings',
  titleTextStrokeEnabled: 'title-text-stroke-enabled',
  titleTextStrokeSettings: 'title-text-stroke',
  artistsDropShadowEnabled: 'artists-drop-shadow',
  artistsDropShadowSettings: 'artists-drop-shadow-settings',
  artistsTextStrokeEnabled: 'artists-text-stroke-enabled',
  artistsTextStrokeSettings: 'artists-text-stroke',
  titleFontSize: 'title-font-size',
  titleFontFamily: 'title-font-family',
  artistsFontSize: 'artists-font-size',
  artistsFontFamily: 'artists-font-family',
  showAlbumArt: 'show-album-art',
};
