export const chatSearchParamsMap = {
  animatedEntry: 'animated-entry',
  backgroundColor: 'background-color',
  height: 'height',
  width: 'width',
  animatedExit: 'animated-exit',
  secondsBeforeExit: 'seconds-before-exit',
  dropShadowEnabled: 'drop-shadow',
  dropShadowSettings: 'drop-shadow-settings',
  foregroundColor: 'foreground-color',
  showAvatars: 'show-avatars',
  showBorders: 'show-borders',
  showColonAfterDisplayName: 'show-colon-after-display-name',
  textStrokeEnabled: 'text-stroke-enabled',
  textStrokeSettings: 'text-stroke',
};
